pretrained_path: openbmb/VoxCPM2
train_manifest: /root/voxcpm-finetune/data/processed/fleurs_tl/train.jsonl
val_manifest: /root/voxcpm-finetune/data/processed/fleurs_tl/val.jsonl
sample_rate: 16000
out_sample_rate: 48000
batch_size: 16
grad_accum_steps: 1
num_workers: 2
num_iters: 1000
log_interval: 10
valid_interval: 500
save_interval: 500
weight_decay: 0.01
warmup_steps: 100
max_batch_tokens: 8192
max_grad_norm: 0.0
learning_rate: 0.0001
lora:
  enable_lm: true
  enable_dit: true
  enable_proj: false
  r: 64
  alpha: 64
  dropout: 0.0
max_steps: 1000
save_path: /root/autodl-tmp/voxft_ckpt/lora_0904_110838
tensorboard: /root/voxcpm-finetune/checkpoints/lora_0904_110838/logs
lambdas:
  loss/diff: 1.0
  loss/stop: 1.0
